config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/loans', to: 'loans#index'
  get '/payment', to: 'payments#new'
  get '/loans/new', to: 'loans#new'

  resources :loans,		only: [:index, :new, :create, :show]
  resources :payments,	only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan.rb
class Loan < ApplicationRecord
  has_many :payments
  validates :customer_name, presence: true
  validates_numericality_of :loan_amount, :greater_than => 5000

  def self.total_Loans
  	Loan.count
  end

  def self.total_Loaned
  	Loan.sum(:loan_amount)
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :loan
  default_scope -> { order(created_at: :desc) }
  validates :loan_id, presence: true
  validates_numericality_of :payment_amount, :greater_than => 0
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def index
    @loans = Loan.paginate(page: params[:page])
  end

  def show
    @loan = Loan.find(params[:id])
    @payments = @loan.payments.paginate(page: params[:page])
  end

  def new
  	@loan = Loan.new
  end

  def create
  	@loan = Loan.new(loan_params)
  	if @loan.save
  		redirect_to @loan
  	else
  		render 'new'
  	end
  end

  private
  	def loan_params
  		params.require(:loan).permit(:customer_name, :loan_amount, :loan_type)
  	end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	def new
		@payment = Payment.new
	end

	def create
		@payment = Payment.new(payment_params)
		if @payment.save
			flash[:success] = "Payment processed!"
			#redirect_to Loan.find(params[:id])
		else
			render 'new'
		end
	end

	def destroy
	end

	private
		def payment_params
			params.require(:payment).permit(:payment_amount)
		end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Chase Bank"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Chase Bank", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Loans",   loans_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :customer_name %>
  <%= f.text_field :customer_name, class: 'form-control' %>

  <%= f.label :loan_amount %>
  <%= f.number_field :loan_amount, class: 'form-control', step: :any %>

  <%= f.label :loan_type %>
  <%= f.select :loan_type, ['AUTO', 'VIVIENDA', 'PERSONAL'], class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/loans/_loan.html.erb
<tr>
  <td><%= link_to loan.id, loan %></td>
  <td><%= loan.customer_name %></td>
  <td>Lps.<%= loan.loan_amount %></td>
  <td><%= loan.loan_type %></td>
</tr>

app/views/loans/index.html.erb
<% provide(:title, 'Loans') %>
<h1>Loans</h1>
<p>This will be a page that will display all Loans.</p>

<%= will_paginate %>

<ul class="loans">
	<table>
	  	<tr>
		  <th>Loan ID</th>
		  <th>Customer Name</th>
		  <th>Loan Amount</th>
		  <th>Loan Type</th>
	  	</tr>
		<%= render @loans %>
	</table>
</ul>

<%= will_paginate %>

<div>
	<%= link_to "Create a new Loan!", '/loans/new', class: "btn btn-lg btn-primary pull-right" %>
</div>

app/views/loans/new.html.erb
<% provide(:title, 'New Loan') %>
<% provide(:button_text, 'Submit new loan') %>
<h1>New Loan</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= render 'form' %>
  </div>
</div>

app/views/loans/show.html.erb
<% provide(:title, @loan.customer_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="loan_info">
        <%= render 'shared/loan_info' %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @loan.payments.any? %>
      <h3>Payments (<%= @loan.payments.count %>)</h3>
      <ol class="payments">
        <%= render @payments %>
      </ol>
      <%= will_paginate @payments %>
    <% else %>
      <h3>You have not made any payments for your loan!</h3>
    <% end %>
  </div>
  <%= link_to "Make a payment!", payment_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.number_field :payment_amount %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/payments/_payment.html.erb
<li id="payment-<%= payment.id %>">
  <span class="loan"><%= link_to payment.loan.customer_name, payment.loan %></span>
  <span class="content"><%= payment.payment_amount %></span>
  <span class="timestamp">
    Paid <%= payment.created_at.strftime("%b %d, %Y") %> ago.
  </span>
</li>

app/views/payments/new.html.erb
<% provide(:title, 'New Loan') %>
<% provide(:button_text, 'Submit new payment') %>
<h1>New Payment</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= render 'form' %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_loan_info.html.erb
<h1><%= @loan.customer_name %></h1>
<span>Loan given on: <%= @loan.created_at.strftime("%b %d, %Y") %></span>
<span>Total amount: <%= @loan.loan_amount %></span>
<span>Loan Type: <%= @loan.loan_type %></span>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Chase Bank</h1>
	<h2>
	  This is the home page for the Chase Bank loaning website.
	</h2>
	<h2>
	  Total loans: <%= Loan.total_Loans %>
	</h2>
	<h2>
	  Total amount loaned: Lps.<%= Loan.total_Loaned %>	
	</h2>
</div>